# Site settings
name: Becky's Home
email: ok_lanyan@163.com
author: Becky
url: 
github: 
baseurl: ""
description: 
meta_description: 
motto: 
banner: 
github_username: ok-lanyan

# 最终输出的路径URL的格式
permalink: /:year-:month-:day/:title.html

# 忽略不想被jekyll处理的文件
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'vendor']

# gitalk评论插件参数
gitalk:
  clientID: 515d1b8811309d7fa2f5
  clientSecret: c6486ffac1517365e50d5cb92e384c4ba99667df
  repo: ok-lanyan.github.io
  owner: ok-lanyan
  admin: ok-lanyan
  pagerDirection: first
  enable: true

# Build settings
markdown: kramdown

# 安装使用的插件
plugins:
  - jekyll-seo-tag
  - jekyll-feed